spring:
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG